# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrctwN-AWdFHgotmPxw7dw-CSmamoqHZ
"""

from .def_fib import fib
from .def_factorial import factorial

__all__ = (
           'fib', 'factorial',
          )