# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrctwN-AWdFHgotmPxw7dw-CSmamoqHZ
"""

from .code import fib
